version: '3.4'

services:
  mfnavbusqueda:
    image: mfnavbusqueda
    build:
      context: mf-nav-busqueda/mf-nav-busqueda
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
